name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          submodules: 'recursive'

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements-test.txt

      - name: Configure and build (Linux / Mac)
        if: runner.os != 'Windows'
        run: |
          cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
          cmake --build build --config Release

      - name: Configure (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake -S . -B build -A x64 -G "Visual Studio 17 2022" -DCMAKE_BUILD_TYPE=Release

      - name: Build (Windows)
        if: runner.os == 'Windows'
        run: |
          cmake --build build --config Release -- /m

      - name: Run tests
        env:
          PYTHONPATH: ${{ (runner.os == 'Windows') && format('{0}\\build\\Release', github.workspace) || format('{0}/build', github.workspace) }}
        run: |
          pytest tests/
